language: cpp

compiler:
    - gcc

script:
    - mkdir build
    - cd build
    - cmake ..
    - make all

addons:
    apt:
        sources:
            - kalakris-cmake
        packages:
            - cmake

